#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <vector>
#include <string>
#include "tdmd/probe/occupancy.hpp"

// M2.5 Tier-1 occupancy probe. Emits a full Markdown report to stdout:
//   ./occupancy_probe > docs/_meta/occupancy_probe_<date>.md
// CUDA-free; on the target GPU plug real specs via flags (from `deviceQuery`).
using namespace tdmd::probe;

int main(int argc, char** argv) {
  // --- defaults: RTX 5080 as MEASURED 2026-06-11 (M2.7 devprobe; was 32
  // blocks/SM provisional — real Blackwell-consumer limit is 24). Still marked
  // provisional until --confirmed, since this binary runs on any host. ---
  DeviceProfile target{"RTX 5080 (Blackwell GB203) — defaults from 2026-06-11 measurement",
                       84, 32, 48, 24, 65536, 102400, true};
  KernelProfile kern{128, 40, 0};
  double zone_width  = 4.0;   // = R_cut (M0)
  double target_fill = 0.5;   // we want a single launch to fill >= 50% of device
  const char* date   = "unset (pass --date)";

  for (int i = 1; i < argc; ++i) {
    auto eat = [&](const char* f) -> const char* {
      return (i + 1 < argc && !std::strcmp(argv[i], f)) ? argv[++i] : nullptr;
    };
    if      (auto v = eat("--sm"))            target.sm_count = atoi(v);
    else if (auto v = eat("--warps-per-sm"))  target.max_warps_per_sm = atoi(v);
    else if (auto v = eat("--blocks-per-sm")) target.max_blocks_per_sm = atoi(v);
    else if (auto v = eat("--smem-block"))    kern.smem_per_block = atol(v);
    else if (auto v = eat("--regs"))          kern.regs_per_thread = atoi(v);
    else if (auto v = eat("--block"))         kern.block_size = atoi(v);
    else if (auto v = eat("--zone-width"))    zone_width = atof(v);
    else if (auto v = eat("--date"))          date = v;
    else if (auto v = eat("--confirmed"))   { target.name = v; target.provisional = false; }
  }

  const Material al{"Al FCC (a=4.05 Å)", 0.06022};  // 72 atoms / golden box

  std::vector<DeviceProfile> devices = {
      target,
      {"A100 (GA100) — reference, approx",     108, 32, 64, 32, 65536, 167936, true},
      {"RTX 4090 (Ada AD102) — reference, approx", 128, 32, 48, 24, 65536, 101376, true},
  };
  const std::vector<long> N = {72, 1000, 10000, 100000, 1000000, 10000000};

  // ---------------- report ----------------
  std::printf("# Occupancy probe report (M2.5 Tier-1%s)\n\n",
              target.provisional ? "" : " · confirmed on device, M2.7 Tier-2");
  std::printf("**Date:** %s · **Generated by:** `occupancy_probe` "
              "(analytical, CUDA-free) · risk **A2**\n\n", date);
  if (target.provisional) {
    std::printf("> ⚠️ **Device specs are PROVISIONAL** (not taken from a live "
                "`deviceQuery` run). Confirm on the target via `tools/devprobe` "
                "and re-run with `--confirmed` + the printed flags. The "
                "**conclusion is robust to the exact numbers** (see sensitivity "
                "section).\n\n");
  } else {
    std::printf("> ✅ **Device specs confirmed from a live device run** "
                "(`tools/devprobe`, M2.7). Kernel resources (regs/thread) remain "
                "an estimate until the M3 prototype kernel (`nvcc -Xptxas -v`).\n\n");
  }

  std::printf("## Inputs\n\n");
  std::printf("- **Material:** %s, number density ρ = %.5f atoms/Å³.\n",
              al.name.c_str(), al.number_density);
  std::printf("- **Zone width:** %.2f Å (= R_cut, M0). A TD zone is a slab of "
              "this width across the box cross-section.\n", zone_width);
  std::printf("- **Kernel estimate:** block_size = %d, %d regs/thread, "
              "%ld B shared-mem/block. *(No compiled kernel yet — M3 will refine "
              "via `nvcc -Xptxas -v`.)*\n", kern.block_size, kern.regs_per_thread,
              kern.smem_per_block);
  std::printf("- **Saturation target:** a single kernel launch should fill ≥ %.0f%% "
              "of the device.\n\n", target_fill * 100);

  // device table
  std::printf("## Device profiles\n\n");
  std::printf("| Device | SMs | warps/SM | blocks/SM | regs/SM | smem/SM (KB) | confirmed |\n");
  std::printf("|--------|----:|---------:|----------:|--------:|-------------:|:---------:|\n");
  for (auto& d : devices)
    std::printf("| %s | %d | %d | %d | %ld | %.0f | %s |\n", d.name.c_str(),
                d.sm_count, d.max_warps_per_sm, d.max_blocks_per_sm, d.regs_per_sm,
                d.smem_per_sm / 1024.0, d.provisional ? "**no**" : "yes");
  std::printf("\n");

  // per-SM occupancy of the kernel
  std::printf("## Per-SM occupancy of the force kernel\n\n");
  std::printf("Theoretical occupancy from kernel resources vs per-SM limits "
              "(independent of problem size).\n\n");
  std::printf("| Device | active blocks/SM | active warps/SM | occupancy | limiter |\n");
  std::printf("|--------|-----------------:|----------------:|----------:|---------|\n");
  for (auto& d : devices) {
    auto o = per_sm_occupancy(d, kern);
    std::printf("| %s | %d | %d | %.0f%% | %s |\n", d.name.c_str(),
                o.active_blocks_per_sm, o.active_warps_per_sm, o.occupancy * 100,
                to_string(o.limiter));
  }
  std::printf("\n> A high per-SM occupancy here does **not** mean the device is "
              "busy: that depends on whether the problem supplies enough warps "
              "(next section). This is the crux of A2.\n\n");

  // device-fill sweep on target
  const auto occ_t = per_sm_occupancy(target, kern);
  std::printf("## Device fill vs system size — %s\n\n", target.name.c_str());
  std::printf("Single thin zone (width %.1f Å), per-SM occupancy %.0f%% "
              "→ device holds %ld warps at once.\n\n",
              zone_width, occ_t.occupancy * 100,
              (long)target.sm_count * occ_t.active_warps_per_sm);
  std::printf("| N atoms | box L (Å) | zones in box | atoms/zone | warps/zone | "
              "single-zone fill | zones to saturate |\n");
  std::printf("|--------:|----------:|-------------:|-----------:|-----------:|"
              "-----------------:|------------------:|\n");
  for (long n : N) {
    auto f = device_fill(n, al, zone_width, target, occ_t);
    std::printf("| %ld | %.0f | %ld | %.0f | %ld | %.1f%% | %ld |\n", n,
                box_side(n, al.number_density), f.n_zones_in_system,
                f.atoms_per_zone, f.warps_per_zone, f.single_zone_fill * 100,
                f.zones_to_saturate);
  }
  std::printf("\n");

  // sensitivity across profiles at one representative size
  const long N_rep = 1000000;
  std::printf("## Sensitivity to device specs (N = %ld)\n\n", N_rep);
  std::printf("The single-zone-underfill conclusion holds across plausible "
              "profiles, so it does not hinge on the provisional 5080 numbers.\n\n");
  std::printf("| Device | device warp cap | warps/zone | single-zone fill | zones to saturate |\n");
  std::printf("|--------|----------------:|-----------:|-----------------:|------------------:|\n");
  for (auto& d : devices) {
    auto o = per_sm_occupancy(d, kern);
    auto f = device_fill(N_rep, al, zone_width, d, o);
    std::printf("| %s | %ld | %ld | %.1f%% | %ld |\n", d.name.c_str(),
                f.device_warp_cap, f.warps_per_zone, f.single_zone_fill * 100,
                f.zones_to_saturate);
  }
  std::printf("\n");

  // verdict
  auto f_rep = device_fill(N_rep, al, zone_width, target, occ_t);
  const bool underfilled = f_rep.single_zone_fill < target_fill;
  const bool batch_ok = f_rep.zones_to_saturate <= f_rep.n_zones_in_system;
  std::printf("## Verdict (go / no-go)\n\n");
  if (underfilled) {
    std::printf("- 🔴 **A single thin zone underutilizes the GPU.** At N=%ld a "
                "%.1f Å zone fills only **%.1f%%** of %s (per-SM occupancy is "
                "%.0f%% — the gap is purely *too few warps in flight*).\n",
                N_rep, zone_width, f_rep.single_zone_fill * 100, target.name.c_str(),
                occ_t.occupancy * 100);
    std::printf("- 🟢 **Batching recovers it.** Running **≈%ld zones concurrently** "
                "per kernel/stream reaches the ≥%.0f%% target (%ld zones available "
                "in the box → %s).\n", f_rep.zones_to_saturate, target_fill * 100,
                f_rep.n_zones_in_system, batch_ok ? "feasible" : "**NOT feasible**");
  } else {
    std::printf("- 🟢 A single zone already fills ≥%.0f%% at N=%ld.\n",
                target_fill * 100, N_rep);
  }
  std::printf("- The tiny golden system (N=72) is a **force-correctness fixture, "
              "not a performance target** — a single zone there is ~1 warp.\n");
  std::printf("- Small/medium systems (≤~10⁶ atoms) underfill on one zone; very "
              "large systems (≥~10⁷) approach saturation on a single zone.\n\n");

  std::printf("### Recommendation for M3\n\n");
  std::printf("1. The clustering/conveyor **must process multiple zones "
              "concurrently** (batch ≈ %ld for the 5080 class) — a one-zone-at-a-time "
              "kernel will leave the GPU idle on typical sizes.\n",
              f_rep.zones_to_saturate);
  std::printf("2. Keep the kernel register-light (it hit %.0f%% per-SM occupancy at "
              "%d regs/thread, block %d).\n", occ_t.occupancy * 100,
              kern.regs_per_thread, kern.block_size);
  std::printf("3. Treat zone width as an occupancy tuning knob (≥ R_cut), not just "
              "a causality parameter.\n\n");

  std::printf("## Reproduce / confirm on target\n\n");
  std::printf("```bash\n");
  std::printf("# Tier-1 (any host, no GPU):\n");
  std::printf("./build/occupancy_probe --date <YYYY-MM-DD> > docs/_meta/occupancy_probe_<date>.md\n\n");
  std::printf("# On the target GPU: tools/devprobe prints the exact flags to feed back:\n");
  std::printf("./build-cuda/devprobe   # -> occupancy_probe flags: --sm ... --blocks-per-sm ...\n");
  std::printf("./build/occupancy_probe --sm <SMs> --warps-per-sm <W> --blocks-per-sm <B> \\\n");
  std::printf("    --regs <regs/thread> --block <block> --date <date> --confirmed \"<name>\"\n");
  std::printf("```\n\n");
  std::printf("**Tier-2 (on GPU, M2.7+):** device limits via `tools/devprobe` "
              "(`cudaGetDeviceProperties` + `cudaOccupancyMaxActiveBlocksPerMultiprocessor` "
              "on a reference kernel); achieved occupancy via Nsight Compute "
              "`sm__warps_active.avg.pct_of_peak_sustained_active` on the real "
              "force kernel — lands with the M3 prototype.\n");
  return 0;
}
